; PlatformIO проект: C3 XLAMPER v0.12 (модульная прошивка)
; Плата: ESP32-C3 Super Mini (ESP32-C3FN4, 4MB flash)
[platformio]
src_dir = src

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
board_build.partitions = partitions_xlamper.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -std=gnu++17
    -Isrc
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCoreDebugLevel=0
    -Wall
    -Wextra
    -Wno-unused-parameter
    ;-Wconversion

lib_deps =
    olikraus/U8g2@^2.35.30

monitor_filters = esp32_exception_decoder

; генерация compile_commands.json для clangd/LSP
; (чтобы линтер видел настоящий тулчейн, а не "Arduino.h not found")
; run_configs =
;   пlatformio генерирует при: pio run --makeflags -f .pio/Makefile
build_type = release
